language: python

python:
  - "3.5.2"

addons:
  apt:
    packages:
    - graphviz

install:
  - pip install -r requirements.txt

script:
  - make clean test doc
  - bin/decompile --help
  - bin/decompile -a examples/dao_hack.dasm
  - bin/decompile -a examples/mem_leak.dasm
  - bin/decompile -a examples/withdraw_dao.dasm
  - bin/decompile examples/dao_hack.hex
  - bin/decompile examples/mem_leak.hex
  - bin/decompile examples/withdraw_dao.hex
  - bin/decompile -b examples/dao_hack.hex
  - bin/decompile -b examples/mem_leak.hex
  - bin/decompile -b examples/withdraw_dao.hex
  - bash -c '[ ! -f graph.pdf ]'
  - bash -c '[ ! -d tsv ]'
  - bin/decompile -g graph.pdf -t tsv -d -b examples/dao_hack.hex
  - bash -c '[ -s graph.pdf ]'
  - bash -c '[ -d tsv ]'
  - bash -c '[ -s tsv/block.facts ]'
  - bash -c '[ -s tsv/def.facts ]'
  - bash -c '[ -s tsv/use.facts ]'
  - bash -c '[ -s tsv/edge.facts ]'
  - bash -c '[ -s tsv/entry.facts ]'
  - bash -c '[ -s tsv/exit.facts ]'
  - bash -c '[ -s tsv/op.facts ]'
  - bash -c '[ -s tsv/value.facts ]'
  - bash -c '[ -s tsv/dom.facts ]'
  - bash -c '[ -s tsv/imdom.facts ]'
  - bash -c '[ -s tsv/pdom.facts ]'
  - bash -c '[ -s tsv/impdom.facts ]'
  - bin/disassemble examples/dao_hack.hex
  - bin/disassemble -p examples/dao_hack.hex
  - bin/disassemble examples/dao_hack.hex | bin/decompile
  - bash -c '[ ! -f basic.tac ]'
  - bin/decompile examples/basic.dasm basic.tac
  - bash -c '[ -s basic.tac ]'
